name: test run
conf: src/config.yaml
confSeq: src/configSeq.yaml
outputDir: output
debug: False
seq: True         # Turns sequential mode on and off
optimize: False     # Turns optimizer mode on and off
optimizer:
  numTrials: 2
  numJobs: 1
successString: ' - finished'
